#include "action.hh"

// Empty constructor and destructor
MyActionInitialization::MyActionInitialization() { }
MyActionInitialization::~MyActionInitialization() { }

void MyActionInitialization::Build() const
{
    // Creates a new generator and sets it as the user action
    // (essentially allows for a particle to be generated by
    // the user)
    MyPrimaryGenerator *generator = new MyPrimaryGenerator();
    SetUserAction(generator);
    
    MyRunAction *runAction = new MyRunAction();
    SetUserAction(runAction);
}
